export let jobs = [
  {
    id: 1,
    title: 'Desarrollador Frontend',
    company: 'Tech Solutions',
    contactPerson: 'Ana López',
    contact: 'ana@tech.com',
    location: 'Madrid, España',
    category: 'tecnologia',
    availability: 'Full-time',
    responsibilities: 'Desarrollo de interfaces con React',
    salary: '$3,000,000 COP',
    type: 'vacancy'
  },
  {
    id: 101,
    occupation: 'Desarrollador Frontend',
    name: 'Juan Pérez',
    documentType: 'Cédula',
    documentNumber: '123456789',
    email: 'juan@example.com',
    phone: '3001234567',
    secondaryPhone: '6012345678',
    municipality: 'Bogotá',
    personalDescription: 'Desarrollador con 3 años de experiencia en React y TypeScript',
    skills: ['React', 'JavaScript', 'CSS', 'Redux'],
    studies: 'Ingeniería de Sistemas - Universidad Nacional',
    type: 'person'
  },
  {
    id: 2,
    title: 'Diseñador Gráfico',
    company: 'Creative Agency',
    contactPerson: 'Carlos Gómez',
    contact: 'carlos@creative.com',
    location: 'Barcelona, España',
    category: 'diseno_web',
    availability: 'Part-time',
    responsibilities: 'Diseño de piezas gráficas para campañas digitales',
    salary: '$2,000,000 COP',
    type: 'vacancy'
  },
  {
    id: 102,
    occupation: 'Diseñador Gráfico',
    name: 'María Rodríguez',
    documentType: 'Cédula',
    documentNumber: '987654321',
    email: 'maria@example.com',
    phone: '3109876543',
    secondaryPhone: '6018765432',
    municipality: 'Medellín',
    personalDescription: 'Diseñadora gráfica especializada en branding y diseño digital',
    skills: ['Photoshop', 'Illustrator', 'Figma', 'After Effects'],
    studies: 'Diseño Gráfico - Universidad de Antioquia',
    type: 'person'
  },
  {
    id: 3,
    title: 'Gerente de Proyectos',
    company: 'Business Corp',
    contactPerson: 'Lucía Martínez',
    contact: 'lucia@businesscorp.com',
    location: 'Valencia, España',
    category: 'administracion',
    availability: 'Full-time',
    responsibilities: 'Gestión de proyectos y liderazgo de equipos multidisciplinarios',
    salary: '$5,500,000 COP',
    type: 'vacancy'
  },
  {
    id: 103,
    occupation: 'Gerente de Proyectos',
    name: 'Carlos Sánchez',
    documentType: 'Pasaporte',
    documentNumber: 'AB123456',
    email: 'carlos@example.com',
    phone: '3201239876',
    secondaryPhone: '6017654321',
    municipality: 'Cali',
    personalDescription: 'PMP certificado con experiencia en gestión de equipos ágiles',
    skills: ['Scrum', 'Kanban', 'JIRA', 'Gestión de presupuestos'],
    studies: 'MBA - Universidad de los Andes',
    type: 'person'
  },
  {
    id: 4,
    title: 'Analista de Datos',
    company: 'Data Insights',
    contactPerson: 'Pedro Ramírez',
    contact: 'pedro@datainsights.com',
    location: 'Sevilla, España',
    category: 'ciencia',
    availability: 'Medio tiempo',
    responsibilities: 'Análisis de datos con Python y Power BI',
    salary: '$1,200,000 COP',
    type: 'vacancy'
  },
  {
    id: 104,
    occupation: 'Analista de Datos',
    name: 'Laura Gómez',
    documentType: 'Cédula',
    documentNumber: '456789123',
    email: 'laura@example.com',
    phone: '3154567890',
    secondaryPhone: '6016543210',
    municipality: 'Barranquilla',
    personalDescription: 'Analista de datos con experiencia en machine learning y visualización',
    skills: ['Python', 'SQL', 'Power BI', 'Pandas', 'Scikit-learn'],
    studies: 'Estadística - Universidad del Norte',
    type: 'person'
  },
  {
    id: 5,
    title: 'Desarrollador Backend',
    company: 'Web Solutions',
    contactPerson: 'Sofía Herrera',
    contact: 'sofia@websolutions.com',
    location: 'Bilbao, España',
    category: 'tecnologia',
    availability: 'Full-time',
    responsibilities: 'Desarrollo de APIs REST con Node.js',
    salary: '$3,200,000 COP',
    type: 'vacancy'
  },
  {
    id: 105,
    occupation: 'Desarrollador Backend',
    name: 'Andrés Martínez',
    documentType: 'Cédula',
    documentNumber: '789123456',
    email: 'andres@example.com',
    phone: '3178901234',
    secondaryPhone: '6015432109',
    municipality: 'Pereira',
    personalDescription: 'Desarrollador backend con experiencia en arquitecturas escalables',
    skills: ['Node.js', 'Express', 'MongoDB', 'Docker', 'AWS'],
    studies: 'Ingeniería de Software - Universidad Tecnológica de Pereira',
    type: 'person'
  },
  {
    id: 6,
    title: 'Especialista en Marketing Digital',
    company: 'Marketing Agency',
    contactPerson: 'Esteban Ruiz',
    contact: 'esteban@marketingagency.com',
    location: 'Málaga, España',
    category: 'marketing',
    availability: 'Part-time',
    responsibilities: 'Planificación de campañas en redes sociales',
    salary: '$2,500,000 COP',
    type: 'vacancy'
  },
  {
    id: 106,
    occupation: 'Especialista en Marketing Digital',
    name: 'Sofía Ramírez',
    documentType: 'Cédula',
    documentNumber: '321654987',
    email: 'sofia@example.com',
    phone: '3187654321',
    secondaryPhone: '6014321098',
    municipality: 'Bucaramanga',
    personalDescription: 'Especialista en marketing digital con enfoque en redes sociales y SEO',
    skills: ['SEO', 'Google Ads', 'Facebook Ads', 'Analítica web'],
    studies: 'Comunicación Social - Universidad Pontificia Bolivariana',
    type: 'person'
  },
  {
    id: 7,
    title: 'Ingeniero de Software',
    company: 'Tech Innovations',
    contactPerson: 'Valeria Torres',
    contact: 'valeria@techinnovations.com',
    location: 'Zaragoza, España',
    category: 'tecnologia',
    availability: 'Full-time',
    responsibilities: 'Desarrollo de soluciones escalables con Java',
    salary: '$4,800,000 COP',
    type: 'vacancy'
  },
  {
    id: 107,
    occupation: 'Ingeniero de Software',
    name: 'David Fernández',
    documentType: 'Pasaporte',
    documentNumber: 'CD789012',
    email: 'david@example.com',
    phone: '3190123456',
    secondaryPhone: '6013210987',
    municipality: 'Manizales',
    personalDescription: 'Ingeniero de software con experiencia en desarrollo empresarial',
    skills: ['Java', 'Spring Boot', 'Microservicios', 'Kubernetes'],
    studies: 'Ingeniería Informática - Universidad de Caldas',
    type: 'person'
  },
  {
    id: 8,
    title: 'Asistente Administrativo',
    company: 'Office Solutions',
    contactPerson: 'Diego Castro',
    contact: 'diego@officesolutions.com',
    location: 'Alicante, España',
    category: 'administracion',
    availability: 'Medio tiempo',
    responsibilities: 'Gestión documental y soporte administrativo',
    salary: '$1,000,000 COP',
    type: 'vacancy'
  },
  {
    id: 108,
    occupation: 'Asistente Administrativo',
    name: 'Patricia López',
    documentType: 'Cédula',
    documentNumber: '654987321',
    email: 'patricia@example.com',
    phone: '3145678901',
    secondaryPhone: '6012109876',
    municipality: 'Cartagena',
    personalDescription: 'Asistente administrativo con experiencia en gestión documental y atención al cliente',
    skills: ['Office', 'Gestión de archivos', 'Atención al cliente', 'Contabilidad básica'],
    studies: 'Administración de Empresas - Universidad de Cartagena',
    type: 'person'
  }
]