export const vacanciesExample = [
    {
        id: 1,
        title: 'Desarrollador Frontend',
        company: 'Tech Solutions',
        location: 'Madrid, España',
        type: 'Full-time',
        experience: '2 años',
    },
    {
        id: 2,
        title: 'Diseñador Gráfico',
        company: 'Creative Agency',
        location: 'Barcelona, España',
        type: 'Part-time',
        experience: '1 año',
    },
    {
        id: 3,
        title: 'Gerente de Proyectos',
        company: 'Business Corp',
        location: 'Valencia, España',
        type: 'Full-time',
        experience: '5 años',
    },
    {
        id: 4,
        title: 'Analista de Datos',
        company: 'Data Insights',
        location: 'Sevilla, España',
        type: 'Internship',
        experience: 'No requerida',
    },
    {
        id: 5,
        title: 'Desarrollador Backend',
        company: 'Web Solutions',
        location: 'Bilbao, España',
        type: 'Full-time',
        experience: '3 años',
    },
    {
        id: 6,
        title: 'Especialista en Marketing Digital',
        company: 'Marketing Agency',
        location: 'Málaga, España',
        type: 'Part-time',
        experience: '2 años',
    },
    {
        id: 7,
        title: 'Ingeniero de Software',
        company: 'Tech Innovations',
        location: 'Zaragoza, España',
        type: 'Full-time',
        experience: '4 años',
    },
    {
        id: 8,
        title: 'Asistente Administrativo',
        company: 'Office Solutions',
        location: 'Alicante, España',
        type: 'Internship',
        experience: 'No requerida',
    },
    {
        id: 9,
        title: 'Desarrollador Móvil',
        company: 'App Development',
        location: 'Granada, España',
        type: 'Full-time',
        experience: '2 años',
    },
    {
        id: 10,
        title: 'Contador Público',
        company: 'Accounting Firm',
        location: 'Murcia, España',
        type: 'Part-time',
        experience: '3 años',
    },
    {
        id: 11,
        title: 'Diseñador UX/UI',
        company: 'Design Studio',
        location: 'Córdoba, España',
        type: 'Full-time',
        experience: '2 años',
    },
    {
        id: 12,
        title: 'Desarrollador de Juegos',
        company: 'Gaming Company',
        location: 'Bilbao, España',
        type: 'Internship',
        experience: 'No requerida',
    }
]