export const users = [
    {
        id: 1,
        documentType: 'Cédula',
        documentNumber: '189123456',
        nameEmployer: 'Carolina Sanchez Torres',
        phoneEmployer: '3030120982',
        phoneSecEmployer: '3030120096',
        emailEmployer: 'carosan80@hotmail.com',
        descEmployer: 'Una persona',
        townEmployer: 'Salento',
        genreEmployer: 'Femenino',
        role: 'Contratante',
    },
    {
        id: 2,
        documentType: 'Cédula',
        documentNumber: '123456789',
        nameJobSeeker: 'Ana López',
        phoneJobSeeker: '3101234567',
        phoneSecJobSeeker: '3101234568',
        emailJobSeeker: 'ana@example.com',
        genreJobSeeker: 'Femenino',
        descJobSeeker: 'Desarrolladora full stack con 5 años de experiencia',
        townJobSeeker: 'Armenia',
        skill1: 'JavaScript',
        skill2: 'React',
        skill3: 'Node.js',
        skill4: 'SQL',
        study1: 'Ingeniería de Sistemas',
        study2: 'Curso de React Avanzado',
        study3: '',
        study4: '',
        role: 'Contratista'
    },
    {
        id: 3,
        nit: '90012345-6',
        nameCompany: 'Constructora XYZ S.A.S.',
        phoneCompany: '3109876543',
        phoneSecCompany: '3109876542',
        emailCompany: 'contacto@constructora.xyz',
        descCompany: 'Una constructora',
        townCompany: 'Armenia',
        genreCompany: 'No aplica (empresa)',
        category: 'Construcción',
        webSite: 'www.constructora.xyz',
        role: 'Empresa',
    }
]