export const users = [
    {
        id: 1,
        documentType: 'Cédula',
        documentNumber: '189123456',
        nameEmployer: 'Carolina Sanchez Torres',
        phoneEmployer: '3030120982',
        phoneSecEmployer: '3030120096',
        emailEmployer: 'carosan80@hotmail.com',
        descEmployer: 'Una persona',
        townEmployer: 'Salento',
        genreEmployer: 'Femenino',
        role: 'contratante',
    },
    {
        id: 2,
        documentType: 'Cédula',
        documentNumber: '194574632',
        nameEmployer: 'Juan Perez Gomez',
        phoneEmployer: '3201234567',
        phoneSecEmployer: '3201234568',
        emailEmployer: 'juanperezgomez@hotmail.com',
        descEmployer: 'Un contratista',
        townEmployer: 'Pijao',
        genreEmployer: 'Masculino',
        skills: ['Electricidad', 'Plomería', 'Carpintería', 'Pintura'],
        studies: ['Bachillerato', 'Técnico en Electricidad'],
        role: 'contratista',
    },
    {
        id: 3,
        documentType: 'NIT',
        documentNumber: '90012345-6',
        nameEmployer: 'Constructora XYZ S.A.S.',
        phoneEmployer: '3109876543',
        phoneSecEmployer: '3109876542',
        emailEmployer: 'contacto@constructora.xyz',
        descEmployer: 'Una constructora',
        townEmployer: 'Armenia',
        genreEmployer: 'No aplica',
        role: 'empresa',
    }
]